---
- name: ensure pgbouncer config dir
  file:
    dest: '{{ item }}'
    state: directory
  with_items:
    - '{{ pgbouncer_config_dir }}'

- name: create pgbouncer configs
  template:
    src: '{{ item }}.j2'
    dest: '{{ pgbouncer_config_dir }}/{{ item }}'
  notify:
    - reload pgbouncer
  with_items:
    - pgbouncer.ini
    - pgbouncer_hba.conf
    - auth.txt

- name: run pgbouncer container
  docker_container:
    state: started
    restart: yes
    recreate: yes
    name: '{{ pgbouncer_container_name }}'
    image: '{{ pgbouncer_image }}:{{ pgbouncer_version }}'
    restart_policy: always
    user: '{{ pgbouncer_user }}'
    published_ports: '{{ pgbouncer_published_ports }}'
    links: '{{ pgbouncer_links }}'
    networks: '{{ pgbouncer_networks }}'
    ulimits: '{{ pgbouncer_ulimits }}'
    sysctls: '{{ pgbouncer_sysctls }}'
    volumes: '{{ pgbouncer_volumes }}'
    env: '{{ pgbouncer_env }}'
